sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/manipulator.html
sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/js/user_system.js
sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/js/vue_components/LessonViewPageTop.js
sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/js/vue_components/IndexPageViewVue.js
sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/js/vue_components/WinModal.js
sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/js/vue_components/ExplorerAIGenerationModal.js
sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/js/vue_components/TutorialModal.js
sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/js/vue_components/CreatorNavigationButtons.js
sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/js/vue_components/SingleLessonDisplay.js
sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/js/vue_components/AlgebraicActionsModalPopup.js
sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/js/vue_components/LessonNavigationModal.js
sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/js/vue_components/NavigationBar.js
sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/js/vue_components/ProfilePageTop.js
sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/js/vue_components/SingleProblemDisplay.js
sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/js/database_management.js
sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/lesson-view.html
sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/creator.html
sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/explorer.html
sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/index.html
sed -i 's/http:\/\/localhost:8080/https:\/\/visualalgebra.org/g' src/site/profile.html